In [3]:
%%time
import numpy as np
import pandas as pd

data_train = pd.read_csv("F:/contest/ATEC/train.csv")
data_test = pd.read_csv("F:/contest/ATEC/test.csv")
# unlabel = data_train[data_train.label == -1].drop(['id'], axis = 1)
data_train = data_train[data_train.label != -1].drop(['id'], axis = 1).sort_values(by = 'date')
# data_train = data_train.drop(['id'], axis = 1)

Wall time: 1min 21s


In [4]:
# data_train = data_train.sort_values(by = 'date')


data_train['ifexist5'] = np.where(data_train.f5.isnull() == True, -1, 1 )
data_train['ifexist20-23'] = np.where(data_train.f20.isnull() == True, -1, 1 )
data_train['ifexist24-27'] = np.where(data_train.f24.isnull() == True, -1, 1)
data_train['ifexist28-31'] = np.where(data_train.f28.isnull() == True, -1, 1)
data_train['ifexist32-35'] = np.where(data_train.f32.isnull() == True, -1, 1)
data_train['ifexist36-47'] = np.where(data_train.f36.isnull() == True, -1, 1)
data_train['ifexist48-51'] = np.where(data_train.f48.isnull() == True, -1, 1)
data_train['ifexist52-53'] = np.where(data_train.f52.isnull() == True, -1, 1)
data_train['ifexist54-63'] = np.where(data_train.f54.isnull() == True, -1, 1)
data_train['ifexist64-71'] = np.where(data_train.f64.isnull() == True, -1, 1)
data_train['ifexist72-75'] = np.where(data_train.f72.isnull() == True, -1, 1)
data_train['ifexist76-101'] = np.where(data_train.f76.isnull() == True, -1, 1)
data_train['ifexist102-106'] = np.where(data_train.f102.isnull() == True, -1, 1)
data_train['ifexist107-110'] = np.where(data_train.f107.isnull() == True, -1, 1)
data_train['ifexist111-154'] = np.where(data_train.f111.isnull() == True, -1, 1)
data_train['ifexist155-160'] = np.where(data_train.f155.isnull() == True, -1, 1)
data_train['ifexist161-165'] = np.where(data_train.f161.isnull() == True, -1, 1)
data_train['ifexist166-210'] = np.where(data_train.f166.isnull() == True, -1, 1)
data_train['ifexist211-253'] = np.where(data_train.f211.isnull() == True, -1, 1)
data_train['ifexist254-277'] = np.where(data_train.f254.isnull() == True, -1, 1)
data_train['ifexist278-297'] = np.where(data_train.f278.isnull() == True, -1, 1)





dt = data_train
data_train = data_test
data_train['ifexist5'] = np.where(data_train.f5.isnull() == True, -1, 1 )
data_train['ifexist20-23'] = np.where(data_train.f20.isnull() == True, -1, 1 )
data_train['ifexist24-27'] = np.where(data_train.f24.isnull() == True, -1, 1)
data_train['ifexist28-31'] = np.where(data_train.f28.isnull() == True, -1, 1)
data_train['ifexist32-35'] = np.where(data_train.f32.isnull() == True, -1, 1)
data_train['ifexist36-47'] = np.where(data_train.f36.isnull() == True, -1, 1)
data_train['ifexist48-51'] = np.where(data_train.f48.isnull() == True, -1, 1)
data_train['ifexist52-53'] = np.where(data_train.f52.isnull() == True, -1, 1)
data_train['ifexist54-63'] = np.where(data_train.f54.isnull() == True, -1, 1)
data_train['ifexist64-71'] = np.where(data_train.f64.isnull() == True, -1, 1)
data_train['ifexist72-75'] = np.where(data_train.f72.isnull() == True, -1, 1)
data_train['ifexist76-101'] = np.where(data_train.f76.isnull() == True, -1, 1)
data_train['ifexist102-106'] = np.where(data_train.f102.isnull() == True, -1, 1)
data_train['ifexist107-110'] = np.where(data_train.f107.isnull() == True, -1, 1)
data_train['ifexist111-154'] = np.where(data_train.f111.isnull() == True, -1, 1)
data_train['ifexist155-160'] = np.where(data_train.f155.isnull() == True, -1, 1)
data_train['ifexist161-165'] = np.where(data_train.f161.isnull() == True, -1, 1)
data_train['ifexist166-210'] = np.where(data_train.f166.isnull() == True, -1, 1)
data_train['ifexist211-253'] = np.where(data_train.f211.isnull() == True, -1, 1)
data_train['ifexist254-277'] = np.where(data_train.f254.isnull() == True, -1, 1)
data_train['ifexist278-297'] = np.where(data_train.f278.isnull() == True, -1, 1)

data_test = data_train
data_train = dt
del dt

In [5]:
col = list(data_train.columns)[2:]
giveup =[]
for i in col:
#     if data_train[i].isnull().sum() > 250000 :
    if data_train[i].isnull().sum() > 200000:
        giveup.append(i)
        
col1 = [i for i in col if i not in giveup]
         

In [9]:
# data_train = data_train.fillna(0)
# data_test = data_test.fillna(0)
num_train = 10
train = []
for i in range(num_train):
    train.append(data_train.iloc[i*100000:i*100000+100000])


In [65]:
%%time
import lightgbm as lgb

lg = []
res = []
for i in range(num_train):
    lg.append(lgb.LGBMClassifier( max_depth = 8, num_leaves =180, n_estimators = 100,  min_child_samples=100))
    lg[i].fit(train[i][col1].as_matrix(),train[i]['label'])
    res.append(lg[i].predict_proba(data_test[col1].as_matrix())[:,1])
    
    


Wall time: 2min 14s


In [58]:
lg[0]

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        learning_rate=0.1, max_depth=-1, min_child_samples=100,
        min_child_weight=0.001, min_split_gain=0.0, n_estimators=100,
        n_jobs=-1, num_leaves=100, objective=None, random_state=None,
        reg_alpha=0.0, reg_lambda=0.0, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=1)

In [69]:
(sum(res)/10 > 0.2).sum()

9572

In [15]:
%%time
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier
import lightgbm as lgb
import xgboost as xgb
from mlxtend.classifier import StackingClassifier 


lg = []
rf = []
lr = []
xgbmodel = []
res = []


for i in range(num_train):
    lg.append(VotingClassifier(estimators = [('1',lgb.LGBMClassifier(max_depth = 8, n_estimators = 60+i%5*10)), 
                                             ('2', lgb.LGBMClassifier(max_depth = 5+i%5, n_estimators = 100))], voting = 'soft'))
    rf.append(RandomForestClassifier(max_depth = 8, n_estimators = 30))
    xgbmodel.append(VotingClassifier(estimators = [('1',xgb.XGBClassifier(max_depth = 8, n_estimators = 60+i%5*10)), 
                                             ('2', xgb.XGBClassifier(max_depth = 5+i%5, n_estimators = 100))], voting = 'soft'))
    lr.append(LogisticRegression(C = 1.0))
clf = []
for i in range(num_train):
#     clf.append( StackingClassifier(classifiers=[lg[i], xgbmodel[i]], 
#                           average_probas=False,  

#                           meta_classifier=lr[i])) 
      clf.append(VotingClassifier(estimators = [('lg',lg[i]), ('xgb',xgbmodel[i])], voting = 'soft'))
      clf[i].fit(train[i][col1].as_matrix(),train[i]['label'])
      res.append(clf[i].predict_proba(data_test[col1].as_matrix())[:,1])

Wall time: 47min 10s


In [5]:
%%time
import lightgbm as lgb
lg1 = []
res = []
for i in range(10):
    lg1.append(lgb.LGBMClassifier(max_depth = 8, n_estimators = 100))
    lg1[i].fit(train[i][col1].as_matrix(),train[i]['label'])
    res.append(lg1[i].predict_proba(data_test[col1].as_matrix())[:,1])

Wall time: 2min 59s


10

In [11]:
(sum(res)/10>0.5).sum()

1450

In [9]:
from sklearn.metrics import roc_curve 

def score(y,pred): 
    fpr, tpr, thresholds = roc_curve(y, pred, pos_label=1) 
    score1=0.4*tpr[np.where(fpr>=0.001)[0][0]]+0.3*tpr[np.where(fpr>=0.005)[0][0]]+0.3*tpr[np.where(fpr>=0.01)[0][0]] 
    return 'selfeval',score1, True

In [21]:
lg = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg.fit(data_train[col1].iloc[:900000].as_matrix(), data_train.label[:900000], eval_set = (data_train[col1].iloc[900000:].as_matrix(), data_train.label[900000:]), eval_metric = score)

[1]	valid_0's binary_logloss: 0.601802	valid_0's selfeval: 0.25746
[2]	valid_0's binary_logloss: 0.527044	valid_0's selfeval: 0.258994
[3]	valid_0's binary_logloss: 0.4648	valid_0's selfeval: 0.281671
[4]	valid_0's binary_logloss: 0.412229	valid_0's selfeval: 0.284569
[5]	valid_0's binary_logloss: 0.367334	valid_0's selfeval: 0.286275
[6]	valid_0's binary_logloss: 0.328715	valid_0's selfeval: 0.286104
[7]	valid_0's binary_logloss: 0.295303	valid_0's selfeval: 0.296164
[8]	valid_0's binary_logloss: 0.266152	valid_0's selfeval: 0.293777
[9]	valid_0's binary_logloss: 0.24071	valid_0's selfeval: 0.296675
[10]	valid_0's binary_logloss: 0.218362	valid_0's selfeval: 0.301023
[11]	valid_0's binary_logloss: 0.198672	valid_0's selfeval: 0.297272
[12]	valid_0's binary_logloss: 0.181283	valid_0's selfeval: 0.301535
[13]	valid_0's binary_logloss: 0.165893	valid_0's selfeval: 0.303495
[14]	valid_0's binary_logloss: 0.152225	valid_0's selfeval: 0.299233
[15]	valid_0's binary_logloss: 0.140094	valid_0

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        learning_rate=0.1, max_depth=8, min_child_samples=100,
        min_child_weight=0.001, min_split_gain=0.0, n_estimators=100,
        n_jobs=-1, num_leaves=31, objective=None, random_state=None,
        reg_alpha=0.0, reg_lambda=0.0, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=1)

In [84]:
end = pd.DataFrame({'id': data_test['id'],'score':sum(res)/10})
end.to_csv("F:/contest/ATEC/timeline_xgb30lgb100_haveminchild_0.426+.csv", index = False)

In [10]:
res

[array([0.00084274, 0.0312468 , 0.00036686, ..., 0.00056901, 0.00031004,
        0.00055294]),
 array([0.00053304, 0.06112723, 0.00028243, ..., 0.00032297, 0.00039515,
        0.00014219]),
 array([1.86102235e-03, 1.27090058e-01, 5.95219412e-04, ...,
        2.00702861e-04, 4.48186683e-04, 1.13130259e-04]),
 array([1.67394872e-03, 1.61323439e-01, 5.06830644e-04, ...,
        8.18434685e-04, 5.80480964e-04, 7.64105518e-05]),
 array([8.65605658e-04, 1.83115461e-01, 1.57741666e-03, ...,
        1.45505803e-04, 3.12946538e-04, 8.23440036e-05]),
 array([3.62671543e-04, 5.78678477e-02, 8.93132720e-04, ...,
        2.11298426e-04, 5.58534670e-04, 7.91286563e-05]),
 array([0.00041591, 0.10000658, 0.00088081, ..., 0.00028433, 0.00125431,
        0.00010774]),
 array([7.95852579e-03, 5.11869595e-01, 6.98330943e-04, ...,
        1.76605382e-04, 2.95090187e-03, 5.26755833e-05]),
 array([1.60666828e-03, 1.90686226e-01, 1.10125948e-03, ...,
        5.95718729e-04, 6.44363982e-04, 1.31257140e-04]),
 

In [13]:
import lightgbm as lgb

lg1 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg2 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg3 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg4 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg5 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg6 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg7 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg8 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg9 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg10 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)


lg1.fit(train1.iloc[:,2:].as_matrix(),train1['label'])
lg2.fit(train2.iloc[:,2:].as_matrix(),train2['label'])
lg3.fit(train3.iloc[:,2:].as_matrix(),train3['label'])
lg4.fit(train4.iloc[:,2:].as_matrix(),train4['label'])
lg5.fit(train5.iloc[:,2:].as_matrix(),train5['label'])
lg6.fit(train6.iloc[:,2:].as_matrix(),train6['label'])
lg7.fit(train7.iloc[:,2:].as_matrix(),train7['label'])
lg8.fit(train8.iloc[:,2:].as_matrix(),train8['label'])
lg9.fit(train9.iloc[:,2:].as_matrix(),train9['label'])
lg10.fit(train10.iloc[:,2:].as_matrix(),train10['label'])



import lightgbm as lgb

lg1 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg2 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg3 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg4 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg5 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg6 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg7 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg8 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg9 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg10 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg11 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg12 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg13 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg14 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg15 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg16 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg17 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg18 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg19 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)
lg20 = lgb.LGBMClassifier(max_depth=8,n_estimators = 100,  min_child_samples=100)

lg1.fit(train1[col1].as_matrix(),train1['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg2.fit(train2[col1].as_matrix(),train2['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg3.fit(train3[col1].as_matrix(),train3['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg4.fit(train4[col1].as_matrix(),train4['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg5.fit(train5[col1].as_matrix(),train5['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg6.fit(train6[col1].as_matrix(),train6['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg7.fit(train7[col1].as_matrix(),train7['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg8.fit(train8[col1].as_matrix(),train8['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg9.fit(train9[col1].as_matrix(),train9['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg10.fit(train10[col1].as_matrix(),train10['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg11.fit(train11[col1].as_matrix(),train11['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg12.fit(train12[col1].as_matrix(),train12['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg13.fit(train13[col1].as_matrix(),train13['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg14.fit(train14[col1].as_matrix(),train14['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg15.fit(train15[col1].as_matrix(),train15['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg16.fit(train16[col1].as_matrix(),train16['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg17.fit(train17[col1].as_matrix(),train17['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg18.fit(train18[col1].as_matrix(),train18['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg19.fit(train19[col1].as_matrix(),train19['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)
lg20.fit(train20[col1].as_matrix(),train20['label'],eval_set = (data_train[col1].iloc[900000:990000].as_matrix(),data_train['label'][900000:990000]), eval_metric = score,verbose = 20)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        learning_rate=0.1, max_depth=8, min_child_samples=100,
        min_child_weight=0.001, min_split_gain=0.0, n_estimators=100,
        n_jobs=-1, num_leaves=31, objective=None, random_state=None,
        reg_alpha=0.0, reg_lambda=0.0, silent=True, subsample=1.0,
        subsample_for_bin=200000, subsample_freq=1)